from .convoguide import CONVOGUIDE_PROMPT
from .specialists import (
    HUMOR_AGENT_PROMPT,
    EMPATHY_AGENT_PROMPT,
    SERIOUS_AGENT_PROMPT,
    STORYWEAVER_AGENT_PROMPT,
    CREATIVITY_AGENT_PROMPT,
    DEBATE_AGENT_PROMPT,
    CLARITY_AGENT_PROMPT,
)

__all__ = [
    "CONVOGUIDE_PROMPT",
    "HUMOR_AGENT_PROMPT",
    "EMPATHY_AGENT_PROMPT",
    "SERIOUS_AGENT_PROMPT",
    "STORYWEAVER_AGENT_PROMPT",
    "CREATIVITY_AGENT_PROMPT",
    "DEBATE_AGENT_PROMPT",
    "CLARITY_AGENT_PROMPT",
]
